export const APP_CONFIG = {
    CANVAS_WIDTH: 900,
    CANVAS_HEIGHT: 550,
    CANVAS_MARGIN: 50,
    CANVAS_ROW_SIZE: 60,
    CANVAS_COLUMN_SIZE: 40,
    CANVAS_STEP_SIZE: 10,
    MIN_YEAR: 1881,
    MAX_YEAR: 2006
};

export const CHART_CONFIG = {
    CANVAS_WIDTH: 1200,
    CANVAS_HEIGHT: 600,
    CANVAS_MARGIN: 50,
    LEFT_MARGIN_BOOST: 34,
    X_TITLE_FROM_BOTTOM: 24,
    GRID_LINES_COUNT: 10,
    LINE_WIDTH: 2,
    POINT_RADIUS: 3,
    AXIS_LINE_WIDTH: 2,
    Y_AXIS_LABELS_COUNT: 5,
    FONT_SIZE: 12,
    FONT_FAMILY: 'Arial',
    TITLE_FONT_SIZE: 14,
    TEXT_OFFSET_X: 10,
    TEXT_OFFSET_Y: 4,
    GRID_LINE_WIDTH: 1,
    X_AXIS_LABEL_OFFSET: 20,
    AXIS_TITLE_OFFSET: 10,
    AXIS_TITLE_ROTATION: -Math.PI / 2,
    AXIS_TITLE_TRANSLATE_X: 15,
    MIN_VALUE_RANGE: 1,
    Y_AXIS_PADDING_PERCENT: 0.05,
    MAX_X_LABELS: 10,
    DEVICE_PIXEL_RATIO: typeof window !== 'undefined' ? window.devicePixelRatio || 1 : 1,
    MILLISECONDS_PER_DAY: 1000 * 60 * 60 * 24,
    DAYS_PER_YEAR: 365,
    DAYS_PER_MONTH: 30,
    MIN_GAP_BETWEEN_LABELS: 8,
    PLOT_BOUNDARY_OFFSET: 2,
    EPSILON: 1e-9,
    DEFAULT_DOWNSAMPLE_POINTS: 1000,
    RENDER_BATCH_SIZE: 50,
    CIRCLE_FULL_ANGLE: 2 * Math.PI,
    VALUE_PRECISION: 1,
    MIN_LABEL_COUNT: 2,
    CANVAS_CENTER_X_DIVISOR: 2,
    CANVAS_CENTER_Y_DIVISOR: 2,
    TEXT_WIDTH_HALF_DIVISOR: 2,
    TRIANGLE_AREA_DIVISOR: 2,
    SHORT_PERIOD_DAYS: 30,
    MEDIUM_PERIOD_DAYS: 365,
    LONG_PERIOD_MULTIPLIER: 5,
    LONG_PERIOD_DAYS: 365 * 5,
    MIN_STEP_DAYS: 1,
    WEEK_STEP_DAYS: 7,
    MONTH_STEP_DAYS: 30,
    YEAR_STEP_DAYS: 365
};

export const CHART_COLORS = {
    GRID: '#e0e0e0',
    AXIS: '#333',
    TEXT: '#666',
    TEMPERATURE: '#ff6b6b',
    PRECIPITATION: '#4ecdc4',
    BACKGROUND: '#fff'
};

export const ERROR_CODES = {
    NETWORK_ERROR: 'NETWORK_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    STORAGE_ERROR: 'STORAGE_ERROR'
};

export const BATCH_CONFIG = {
    DEFAULT_BATCH_SIZE: 100,
    DEFAULT_QUEUE_ID: 'default'
};